### ISSUE TITLE
`GROUP BY` support

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#32]

**Comment by gvos94** [comment]
Will take a shot at this.

**Comment by jussisaurio** [comment]
Closing this after #309 , let's open new issues for specific things about the implementation that dont work (of which there are plenty)

**Comment by surfmuggle** [comment]
@jussisaurio A question and maybe a feature suggestion. To my knowledge GROUP BY for sqlite behaves different then other databases and what ANSI SQL /  [ISO/IEC 9075:2016](https://en.wikipedia.org/wiki/ISO_9075) demands.

Is there a plan to allow users to enable a strict mode in Limbo / Turso? 

This mode would determine whether queries and their results conform to the SQL standard or follow SQLite's current behavior.

**Comment by jussisaurio** [comment]
remind me what would a strict mode look like? i'm all for more strictness, dont really care for sqlite's quirks :)

**Comment by surfmuggle** [comment]
The `SQLite` quirks documentation explains [Aggregate Queries Can Contain Non-Aggregate Result Columns That Are Not In The GROUP BY Clause](https://sqlite.org/quirks.html#aggregate_queries_can_contain_non_aggregate_result_columns_that_are_not_in_the_group_by_clause). A `strict mode` could be set up similar to other [pragma commands](https://sqlite.org/pragma.html#toc). To quote from the [quirks page ](https://sqlite.org/quirks.html):

> Applications can activate foreign key enforcement at run-time using the [PRAGMA foreign_keys](https://sqlite.org/pragma.html#pragma_foreign_keys) statement. Or, foreign key enforcement can be activated at compile-time using the [-DSQLITE_DEFAULT_FOREIGN_KEYS=1](https://sqlite.org/compile.html#default_foreign_keys) compile-time option.

A strict mode or `enforce ansi compliance mode` could be set up similar

```bash
-DSQLITE_DEFAULT_ANSI_COMPLIANCE=1 # at compile time
PRAGMA ANSI_COMPLIANCE # at run time
```

Maybe this feature could be discussed with the SQLite team to clarify if SQLite and `Limbo / Turso` could develop in the same direction or to avoid name collisions `TURSO_DEFAULT_ANSI_COMPLIANCE` instead of `DSQLITE_DEFAULT_ANSI_COMPLIANCE`

In [PRAGMA to opt into PRIMARY KEY NOT NULL constraints](https://sqlite.org/forum/forumpost/54b2ec1e4c95e80c1ade0abb5dcf51bc2a899cfe4ff4fa496e4e40730dc64693) besides [using `STRICT Tables`](https://sqlite.org/stricttables.html) a user stated 

> I have earlier made the wish of an COMPATIBILITY_LEVEL pragma, to disable all the quirks that exist in SQLite only due to backwards compatibility.
>
> When you start a new project, it would be nice to avoid all quirks that could be easily avoided with a simple switch.
>
> I do understand that such a behavior can probably never be the default, but it would avoid so much confusion, head scratching and workarounds and if done at compile-time even make SQLite lighter.

**Comment by jussisaurio** [comment]
i think non-aggregate non-groupby columns are also supported in at least some other popular engines, but not enabled by default. Which is good.

**Comment by jussisaurio** [comment]
Disabling them is also going to be really easy, so I'm all for it.
